
<!-- Si la ville n'a pas était trouvé il va dans dans la condition pour ensuite informé que la ville n'a pas était trouvé -->

<?php 
if (!empty($message)) {
	echo $message; 
}
?>

<!-- <?php
echo "<pre>";
	var_dump($responses);
echo "</pre>";
?> -->
<div class="site-content">
	<div class="site-header">
		<div class="container">
			<a href="/album" class="branding">
				<img src="images/logo.png" alt="" class="logo">
				<div class="logo-type">
					<h1 class="site-title">Habiméteo</h1>
					<small class="site-description">Test technique</small>
				</div>
			</a>

			<div class="main-navigation">
				<button type="button" class="menu-toggle"><i class="fa fa-bars"></i></button>
				<ul class="menu">
					<li class="menu-item current-menu-item"><a href="/album">Accueil</a></li>
				</ul> 
			</div>
			<div class="mobile-navigation"></div>

		</div>
	</div> 
	
	<div class="hero" data-bg-image="images/banner.png">
		<div class="container">
			<form action="/album" class="find-location" method="GET">
				<input type="text" placeholder="Tapez votre ville ou votre département" id="autocomplete" name="q">
				<input type="submit" value="Quel temps fait-il ?">
			</form>

		</div>
	</div>
	<div class="forecast-table">
		<div class="container">
			<div class="forecast-container">
				<div class="today forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list']['0']['dt_txt']))?> </div>
						<div class="date"><?= date('d M', strtotime($responses['list']['0']['dt_txt']))?></div>
					</div> 
					<div class="forecast-content">
						<div class="location"><?= $responses['city']['name'] ?></div>
						<div class="degree">
							<div class="num"><?= round($responses['list'][0]['main']['temp_min'])?><sup>o</sup>C</div>
							<div class="forecast-icon">
								<img src="images/icons/<?= $responses['list'][0]['weather'][0]['main']?>.svg" alt="" widt_txth=90>
							</div>	
						</div>
						<span><img src="images/icon-wind.png" alt=""><?= round($responses['list']['0']['wind']['speed'] * 18 / 5)?> km/h</span>
					</div>
				</div>
				<div class="forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list'][9]['dt_txt']))?></div>
					</div> 
					<div class="forecast-content">
						<div class="forecast-icon">
							<img src="images/icons/<?= $responses['list'][1]['weather'][0]['main']?>.svg" alt="" widt_txth=48>
						</div>
						<div class="degree"><?= round(($responses['list'][1]['main']['temp_min'] ))?><sup>o</sup>C</div>
						<small><?= round(($responses['list'][1]['main']['temp_max'] ))?><sup>o</sup></small>
					</div>
				</div>
				<div class="forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list'][15]['dt_txt']))?></div>
					</div>
					<div class="forecast-content">
						<div class="forecast-icon">
							<img src="images/icons/<?= $responses['list'][2]['weather'][0]['main']?>.svg" alt="" widt_txth=48>
						</div>
						<div class="degree"><?= round(($responses['list'][2]['main']['temp_min'] ))?><sup>o</sup>C</div>
						<small><?= round(($responses['list'][2]['main']['temp_max'] ))?><sup>o</sup></small>
					</div>
				</div>
				<div class="forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list'][19]['dt_txt']))?></div>
					</div>
					<div class="forecast-content">
						<div class="forecast-icon">
							<img src="images/icons/<?= $responses['list'][3]['weather'][0]['main']?>.svg" alt="" widt_txth=48>
						</div>
						<div class="degree"><?= round(($responses['list'][3]['main']['temp_min'] ))?><sup>o</sup>C</div>
						<small><?= round(($responses['list'][3]['main']['temp_max'] ))?><sup>o</sup></small>
					</div>
				</div>
				<div class="forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list'][23]['dt_txt']))?></div>
					</div> 
					<div class="forecast-content">
						<div class="forecast-icon">
							<img src="images/icons/<?= $responses['list'][4]['weather'][0]['main']?>.svg" alt="" widt_txth=48>
						</div>
						<div class="degree"><?= round(($responses['list'][4]['main']['temp_min'] ))?><sup>o</sup>C</div>
						<small><?= round(($responses['list'][4]['main']['temp_max'] ))?><sup>o</sup></small>
					</div>
				</div>
				<div class="forecast">
					<div class="forecast-header">
						<div class="day"><?= date('l', strtotime($responses['list'][31]['dt_txt']))?></div>
					</div>
					<div class="forecast-content">
						<div class="forecast-icon">
							<img src="images/icons/<?= $responses['list'][5]['weather'][0]['main']?>.svg" alt="" widt_txth=48>
						</div>
						<div class="degree"><?= round(($responses['list'][5]['main']['temp_min'] ))?><sup>o</sup>C</div>
						<small><?= round(($responses['list'][5]['main']['temp_max'] ))?><sup>o</sup></small>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- <div id="map"> -->
	<!-- </div> -->
	<footer class="site-footer">
		<div class="container">
			<div class="row">
				<div class="col-md-9 col-md-offset-5"">
					<p class="colophon">Réaliser par Youssef ZAKRAOUI</p>
				</div>
			</div>

		</div>
	</footer>
</div>
